services:
  api:
    container_name: '${COMPOSE_PROJECT_NAME}_api'
    restart: always
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - apps/api/.env
    networks:
      - sail
    environment:
      HOST: api
      NODE_ENV: production
      DB_HOST: pgsql

  proxy:
    container_name: '${COMPOSE_PROJECT_NAME}_proxy'
    restart: always
    build:
      context: ./.github/docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./.github/docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    networks:
      - sail
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - PORT=3333
      
  pgsql:
    ports: []
    restart: always